name: Testing

on:
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  lint_api:
    name: Lint API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: Linting
        run: dotnet format --verify-no-changes

  test_api:
    name: Test API
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
      - name: Tools
        run: dotnet tool restore

      - name: Tests
        run: dotnet test --configuration Release --collect:"XPlat Code Coverage" --results-directory ./coverage

      - name: Generate Coverage Report
        run: dotnet reportgenerator -reports:coverage/**/*.xml -targetdir:coveragereport -reporttypes:MarkdownSummaryGithub
      - name: Report Summary
        run: cat coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
